export enum VKCode {
  None = "None",
  Alpha0 = "Alpha0",   // 0 键
  Alpha1 = "Alpha1",
  Alpha2 = "Alpha2",
  Alpha3 = "Alpha3",
  Alpha4 = "Alpha4",
  Alpha5 = "Alpha5",
  Alpha6 = "Alpha6",
  Alpha7 = "Alpha7",
  Alpha8 = "Alpha8",
  Alpha9 = "Alpha9",
  Keypad0 = "Keypad0",  // 数字键盘 0 键
  Keypad1 = "Keypad1",
  Keypad2 = "Keypad2",
  Keypad3 = "Keypad3",
  Keypad4 = "Keypad4",
  Keypad5 = "Keypad5",
  Keypad6 = "Keypad6",
  Keypad7 = "Keypad7",
  Keypad8 = "Keypad8",
  Keypad9 = "Keypad9",
  F1 = "F1",
  F2 = "F2",
  F3 = "F3",
  F4 = "F4",
  F5 = "F5",
  F6 = "F6",
  F7 = "F7",
  F8 = "F8",
  F9 = "F9",
  F10 = "F10",
  F11 = "F11",
  F12 = "F12",
  Enter = "Enter",    // VK_RETURN 输入键
  Space = "Space",    // 空格键
  Backspace = "Backspace", // VK_BACK
  Tab = "Tab",
  Esc = "Esc",      // VK_ESCAPE
  Insert = "Insert",
  Delete = "Delete",
  Home = "Home",
  End = "End",
  Pause = "Pause",
  PageUp = "PageUp",   // VK_PRIOR
  PageDown = "PageDown", // VK_NEXT
  UpArrow = "UpArrow",  // VK_UP
  DownArrow = "DownArrow", // VK_DOWN
  LeftArrow = "LeftArrow", // VK_LEFT
  RightArrow = "RightArrow", // VK_RIGHT
}
