//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiChartManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaiChartManager.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find paired ACB file: {0}.
        /// </summary>
        internal static string AcbNotFound {
            get {
                return ResourceManager.GetString("AcbNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACB file must be paired with AWB file.
        /// </summary>
        internal static string AcbRequiresAwb {
            get {
                return ResourceManager.GetString("AcbRequiresAwb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code invalid.
        /// </summary>
        internal static string ActivationCodeInvalid {
            get {
                return ResourceManager.GetString("ActivationCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium features activated, thank you.
        /// </summary>
        internal static string ActivationSuccess {
            get {
                return ResourceManager.GetString("ActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AquaMai configuration file appears corrupted....
        /// </summary>
        internal static string AquaMaiConfigCorrupted {
            get {
                return ResourceManager.GetString("AquaMaiConfigCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AquaMai is not installed.
        /// </summary>
        internal static string AquaMaiNotInstalled {
            get {
                return ResourceManager.GetString("AquaMaiNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Files|*.wav;*.mp3;*.aac;*.ogg;*.flac;*.m4a;*.wma;*.ape;*.acb;*.awb;*.mp4.
        /// </summary>
        internal static string AudioFileFilter {
            get {
                return ResourceManager.GetString("AudioFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file not found.
        /// </summary>
        internal static string AudioFileNotFound {
            get {
                return ResourceManager.GetString("AudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find paired AWB file: {0}.
        /// </summary>
        internal static string AwbNotFound {
            get {
                return ResourceManager.GetString("AwbNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser window not initialized.
        /// </summary>
        internal static string BrowserNotInitialized {
            get {
                return ResourceManager.GetString("BrowserNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM equals 0.
        /// </summary>
        internal static string ChartBpmZero {
            get {
                return ResourceManager.GetString("ChartBpmZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse chart difficulty {0}.
        /// </summary>
        internal static string ChartDifficultyParseFailed {
            get {
                return ResourceManager.GetString("ChartDifficultyParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart file not exist.
        /// </summary>
        internal static string ChartFileNotFound {
            get {
                return ResourceManager.GetString("ChartFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed some minor errors in chart difficulty {0}.
        /// </summary>
        internal static string ChartFixedMinorErrors {
            get {
                return ResourceManager.GetString("ChartFixedMinorErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart difficulty {0} contains {1}-note division, this value cannot exceed 384. Most cases can be fixed by modifying the chart.
        /// </summary>
        internal static string ChartInvalidMeasure {
            get {
                return ResourceManager.GetString("ChartInvalidMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaiLib error parsing chart difficulty {0}:
        ///{1}
        ///This is usually caused by non-standard syntax in the chart. You can try to fix the chart based on this error message..
        /// </summary>
        internal static string ChartMaiLibParseError {
            get {
                return ResourceManager.GetString("ChartMaiLibParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like some notes were lost! This is likely a bug. We&apos;d really appreciate it if you could provide the chart file!.
        /// </summary>
        internal static string ChartNotesMissing {
            get {
                return ResourceManager.GetString("ChartNotesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse chart difficulty {0} despite all attempts, please check if the chart has issues.
        /// </summary>
        internal static string ChartParseFailed {
            get {
                return ResourceManager.GetString("ChartParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart parsing failed (global).
        /// </summary>
        internal static string ChartParseFailedGlobal {
            get {
                return ResourceManager.GetString("ChartParseFailedGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse chart.
        /// </summary>
        internal static string ChartParseGenericError {
            get {
                return ResourceManager.GetString("ChartParseGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart shift ShiftByOffset encountered an issue.
        /// </summary>
        internal static string ChartShiftByOffsetError {
            get {
                return ResourceManager.GetString("ChartShiftByOffsetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an issue while shifting the chart. Try enabling &quot;Avoid shifting chart&quot; in advanced import options.
        /// </summary>
        internal static string ChartShiftError {
            get {
                return ResourceManager.GetString("ChartShiftError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even after fixing known errors, MaiLib still cannot parse chart difficulty {0}. Falling back to AstroDX&apos;s SimaiSharp parser.
        ///If you notice any issues with the conversion result, you can try testing it in AstroDX and let us know (though this is optional).
        /// </summary>
        internal static string ChartSimaiSharpFallback {
            get {
                return ResourceManager.GetString("ChartSimaiSharpFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file appears corrupted... Reset to default.
        /// </summary>
        internal static string ConfigCorrupted {
            get {
                return ResourceManager.GetString("ConfigCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something&apos;s Wrong.
        /// </summary>
        internal static string ConfigCorruptedTitle {
            get {
                return ResourceManager.GetString("ConfigCorruptedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion failed: {0}.
        /// </summary>
        internal static string ConvertFailed {
            get {
                return ResourceManager.GetString("ConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion complete!.
        /// </summary>
        internal static string ConvertSuccess {
            get {
                return ResourceManager.GetString("ConvertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string DifficultyAdvanced {
            get {
                return ResourceManager.GetString("DifficultyAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string DifficultyBasic {
            get {
                return ResourceManager.GetString("DifficultyBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string DifficultyExpert {
            get {
                return ResourceManager.GetString("DifficultyExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chart with difficulty {0} will be ignored.
        /// </summary>
        internal static string DifficultyIgnored {
            get {
                return ResourceManager.GetString("DifficultyIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chart with difficulty {0} will be imported as Basic.
        /// </summary>
        internal static string DifficultyImportedAsBasic {
            get {
                return ResourceManager.GetString("DifficultyImportedAsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chart with difficulty {0} will be imported as Master.
        /// </summary>
        internal static string DifficultyImportedAsMaster {
            get {
                return ResourceManager.GetString("DifficultyImportedAsMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chart with difficulty {0} will be imported as Re:Master.
        /// </summary>
        internal static string DifficultyImportedAsReMaster {
            get {
                return ResourceManager.GetString("DifficultyImportedAsReMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string DifficultyMaster {
            get {
                return ResourceManager.GetString("DifficultyMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re:Master.
        /// </summary>
        internal static string DifficultyReMaster {
            get {
                return ResourceManager.GetString("DifficultyReMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0} music tracks....
        /// </summary>
        internal static string ExportingMultipleMusic {
            get {
                return ResourceManager.GetString("ExportingMultipleMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string FileNotSelected {
            get {
                return ResourceManager.GetString("FileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed.
        /// </summary>
        internal static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game directory not specified.
        /// </summary>
        internal static string GameDirNotSpecified {
            get {
                return ResourceManager.GetString("GameDirNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get game version, A000\DataConfig.xml may be missing or invalid.
        /// </summary>
        internal static string GameVersionError {
            get {
                return ResourceManager.GetString("GameVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get game version, failed to parse data.
        /// </summary>
        internal static string GameVersionNotFound {
            get {
                return ResourceManager.GetString("GameVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string GameVersionNotFoundTitle {
            get {
                return ResourceManager.GetString("GameVersionNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre with same ID already exists in this directory.
        /// </summary>
        internal static string GenreIdExists {
            get {
                return ResourceManager.GetString("GenreIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre with same ID exists in higher priority directory, new genre won&apos;t be recognized
        ///If you really want to create it, please delete the existing genre in the following directories first.
        /// </summary>
        internal static string GenreIdExistsHigherPriority {
            get {
                return ResourceManager.GetString("GenreIdExistsHigherPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will import the following difficulties: .
        /// </summary>
        internal static string ImportingDifficulties {
            get {
                return ResourceManager.GetString("ImportingDifficulties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing data directory.
        /// </summary>
        internal static string InitDataDirError {
            get {
                return ResourceManager.GetString("InitDataDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string LauncherExit {
            get {
                return ResourceManager.GetString("LauncherExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Directory.
        /// </summary>
        internal static string LauncherGameDir {
            get {
                return ResourceManager.GetString("LauncherGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Login.
        /// </summary>
        internal static string LauncherNeedLogin {
            get {
                return ResourceManager.GetString("LauncherNeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open to LAN.
        /// </summary>
        internal static string LauncherOpenToLan {
            get {
                return ResourceManager.GetString("LauncherOpenToLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically run in server mode and minimize to the system tray upon startup..
        /// </summary>
        internal static string LauncherOpenToLanDesc {
            get {
                return ResourceManager.GetString("LauncherOpenToLanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Game Directory.
        /// </summary>
        internal static string LauncherSelectGameDir {
            get {
                return ResourceManager.GetString("LauncherSelectGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string LauncherStart {
            get {
                return ResourceManager.GetString("LauncherStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on Boot.
        /// </summary>
        internal static string LauncherStartup {
            get {
                return ResourceManager.GetString("LauncherStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string LauncherStop {
            get {
                return ResourceManager.GetString("LauncherStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load genre data {0}: {1}.
        /// </summary>
        internal static string LoadGenreDataFailed {
            get {
                return ResourceManager.GetString("LoadGenreDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load music data {0}: {1}.
        /// </summary>
        internal static string LoadMusicDataFailed {
            get {
                return ResourceManager.GetString("LoadMusicDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load version data {0}: {1}.
        /// </summary>
        internal static string LoadVersionDataFailed {
            get {
                return ResourceManager.GetString("LoadVersionDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing individual difficulty charts is not supported when using maidata. All difficulties will be replaced at once..
        /// </summary>
        internal static string MaidataReplaceAllOnly {
            get {
                return ResourceManager.GetString("MaidataReplaceAllOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music with this ID already exists in current directory.
        /// </summary>
        internal static string MusicIdExists {
            get {
                return ResourceManager.GetString("MusicIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music has no charts.
        /// </summary>
        internal static string MusicNoCharts {
            get {
                return ResourceManager.GetString("MusicNoCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music has no title.
        /// </summary>
        internal static string MusicNoTitle {
            get {
                return ResourceManager.GetString("MusicNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution! This &quot;Replace Chart&quot; function should only be used when modifying the note content of the existing chart, while the audio remains unchanged, the &amp;first offset remains unchanged, and the timing of the first note remains unchanged. Otherwise, you will need to delete the entire chart and re-import it..
        /// </summary>
        internal static string NotesReplacementWarning {
            get {
                return ResourceManager.GetString("NotesReplacementWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter activation code.
        /// </summary>
        internal static string OfflineActivationPrompt {
            get {
                return ResourceManager.GetString("OfflineActivationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Activation.
        /// </summary>
        internal static string OfflineActivationTitle {
            get {
                return ResourceManager.GetString("OfflineActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Path contains special characters or non-ASCII characters, may cause compatibility issues with tools like MelonLoader. Please move to an ASCII path!.
        /// </summary>
        internal static string PathContainsSpecialChars {
            get {
                return ResourceManager.GetString("PathContainsSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string PathContainsSpecialCharsTitle {
            get {
                return ResourceManager.GetString("PathContainsSpecialCharsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected path does not exist!.
        /// </summary>
        internal static string PathNotExist {
            get {
                return ResourceManager.GetString("PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected path doesn&apos;t appear to contain game files, please select the folder containing Sinmai.exe.
        /// </summary>
        internal static string PathNotGameDir {
            get {
                return ResourceManager.GetString("PathNotGameDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select resource directory (OPT).
        /// </summary>
        internal static string SelectAssetDirectory {
            get {
                return ResourceManager.GetString("SelectAssetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select audio file to convert.
        /// </summary>
        internal static string SelectAudioToConvert {
            get {
                return ResourceManager.GetString("SelectAudioToConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select target location.
        /// </summary>
        internal static string SelectTargetLocation {
            get {
                return ResourceManager.GetString("SelectTargetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select video file to convert.
        /// </summary>
        internal static string SelectVideoToConvert {
            get {
                return ResourceManager.GetString("SelectVideoToConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select folder containing jacket images.
        /// </summary>
        internal static string SelectImageFolder {
            get {
                return ResourceManager.GetString("SelectImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid images found.
        /// </summary>
        internal static string NoValidImagesFound {
            get {
                return ResourceManager.GetString("NoValidImagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format.
        /// </summary>
        internal static string UnsupportedChartFormat {
            get {
                return ResourceManager.GetString("UnsupportedChartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible configuration file version.
        /// </summary>
        internal static string UnsupportedConfigVersion {
            get {
                return ResourceManager.GetString("UnsupportedConfigVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported image format.
        /// </summary>
        internal static string UnsupportedImageFormat {
            get {
                return ResourceManager.GetString("UnsupportedImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version with same ID already exists in this directory.
        /// </summary>
        internal static string VersionIdExists {
            get {
                return ResourceManager.GetString("VersionIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version with same ID exists in higher priority directory, new version won&apos;t be recognized
        ///If you really want to create it, please delete the existing version in the following directories first.
        /// </summary>
        internal static string VersionIdExistsHigherPriority {
            get {
                return ResourceManager.GetString("VersionIdExistsHigherPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video or Image|*.mp4;*.mov;*.avi;*.mkv;*.jpg;*.jpeg;*.png;*.gif;*.bmp;*.webp;*.svg;*.dat;*.usm.
        /// </summary>
        internal static string VideoFileFilter {
            get {
                return ResourceManager.GetString("VideoFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 runtime not installed, may result in blank screen...
        ///
        ///If you believe WebView2 is installed, try restarting your computer.
        ///
        ///Would you like to install WebView2?.
        /// </summary>
        internal static string WebView2NotInstalled {
            get {
                return ResourceManager.GetString("WebView2NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView2 Not Installed.
        /// </summary>
        internal static string WebView2NotInstalledTitle {
            get {
                return ResourceManager.GetString("WebView2NotInstalledTitle", resourceCulture);
            }
        }
    }
}
